name: CI

on:
  push:
    branches: [ master, develop, release/* ]
  pull_request:
    branches: [ master ]

jobs:
  build-project:
    strategy:
      matrix:
        runs-on: [windows-latest, ubuntu-latest]
        configuration: [Release, Debug]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.201
    - name: Install dependencies
      run: dotnet restore
      working-directory: Source
    - name: Build site in ${{ matrix.configuration }} mode
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      working-directory: Source
    - name: Test in ${{ matrix.configuration }} mode
      run: dotnet test -c ${{ matrix.configuration }} --no-restore --verbosity normal
      working-directory: Source
